[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn run:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
aptPkgs = ["python3-dev", "zlib1g-dev", "libjpeg-dev", "libpng-dev"] 